// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77MAe6dgsejrbCYSso5Lt1YEs9C0X5ZE',
    appId: '1:589607807711:web:fba26fdee3ad073792576a',
    messagingSenderId: '589607807711',
    projectId: 'verona-app',
    authDomain: 'verona-app.firebaseapp.com',
    storageBucket: 'verona-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5KXsDIdM7_VRaBqhUva2ixsXKM2r1ppQ',
    appId: '1:589607807711:android:4491e7790dd5e76b92576a',
    messagingSenderId: '589607807711',
    projectId: 'verona-app',
    storageBucket: 'verona-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Mqbs7YrLGojClOhY9MMxgTamveIszXo',
    appId: '1:589607807711:ios:19978281d41e1d8d92576a',
    messagingSenderId: '589607807711',
    projectId: 'verona-app',
    storageBucket: 'verona-app.appspot.com',
    iosClientId: '589607807711-21nfq3l449r97amk9o27qv0venlccm3v.apps.googleusercontent.com',
    iosBundleId: 'com.edrex.veronapp',
  );
}
